run:
	clang++ crack_file.cpp -I /opt/homebrew/Cellar/sfml@2/2.6.2_1/include -o main                       \
	-L /opt/homebrew/Cellar/sfml@2/2.6.2_1/lib -lsfml-graphics -lsfml-window -lsfml-system -std=c++17   \
	&& ./main
